### ISSUE TITLE
Shiny app me donne une url mais rien ne s'affiche

### ISSUE THREAD

**Issue by B-Gendron** [B-Gendron/lhp#1]
Bonjour @b-rodrigues,

Je viens de dockerizer mon application Shiny, basée sur un package que j'ai précédemment développé. J'ai fini par réussir à avoir quelque chose qui tourne sans erreur, mais **je n'arrive pas à voir mon application une fois le code exécuté**. Quand je suis les instructions du README de ce repo, le code R tourne et j'obtiens finalement : 
```
Listening on http://127.0.0.1:6451
```
Sauf qu'aucune fenêtre ne s'ouvre dans mon navigateur. Je pense qu'il y a un problème avec le port que j'ai défini, mais je n'arrive pas vraiment à comprendre comment je pourrais résoudre ça. Pourriez-vous m'aider s'il vous plaît ? 

Pour info, j'ai construit le dockerfile à partir de l'image M1 que j'ai construite en cours.

**Comment by b-rodrigues** [comment]
Bonjour

et si vous pointez votre navigateur web sur http://127.0.0.1:6451 il se passe quoi?

**Comment by B-Gendron** [comment]
J'ai un erreur : Safari ne parvient pas à ouvrir la page

**Comment by b-rodrigues** [comment]
Ah oui, parce que cette url c'est qu'à l'intérieur de Docker qu'elle est valable.

Je vois dans le Dockerfile que vous avez exposé 3838, donc essayez:

http://localhost:3838

**Comment by B-Gendron** [comment]
Je n'arrive pas à me connecter au serveur localhost

**Comment by b-rodrigues** [comment]
Ok, je vois qu'il faut d'autres ajustements: il faudrait changer la dernière ligne du Dockerfile en:

```
CMD R -e 'shiny::runApp("app.R", port = 3838, host = "0.0.0.0")'
```

au lieu de 

```
CMD R -e "shiny::runApp('/home/app')"
```

et lancer l'app avec:

```
docker run --rm -p 3838:3838 --name lhp_app image_app  
``` 

EDIT: oubliez pas de rebuild l'image après avoir changé le dockerfile

**Comment by B-Gendron** [comment]
J'ai bien modifié le dockerfile et relancé toutes les commandes. Maintenant il m'affiche

```
Listening on http://0.0.0.0:3838
```

Mais j'ai toujours l'erreur que je ne peux pas accéder à la page

**Comment by B-Gendron** [comment]
Oh pardon autant pour moi ! Avec l'url localhost ça marche !

**Comment by b-rodrigues** [comment]
Reste plus qu'à mettre le Readme à jour, et c'est bon! Je vais essayer de faire tourner l'app chez moi en partant d'une image pour amd64

**Comment by b-rodrigues** [comment]
Super, l'app marche nickel!

Pour une architecture intel/amd j'ai changé la première ligne du Docker en:

```
FROM brodriguesco/r421_rap:version1
```

et ça tourne sans aucun soucis, top!

Ce qui serait intéressant, c'est de rajouter le Dockerfile de l'image `bgendron/r421_m1` dans un sous-dossier, et peut etre signaler dans le Readme que cette image-ci se base sur `bgendron/r421_m1`, comme ça les utilisateurs ont tout au même endroit.

**Comment by B-Gendron** [comment]
Super! Et donc je peux préciser dans le Readme que ça ne tourne que sur un M1 tel que c'est construit, et expliquer comment faire si on veut le faire tourner sur une autre architecture ?

**Comment by b-rodrigues** [comment]
Vous pouvez rajouter la ligne 

```
# If you are not using an M1 Apple computer, uncomment  the following line
#FROM brodriguesco/r421_rap:version1
``` 

dans le Dockerfile, et attirer l'attention des utilisateurs dans le Readme.
