### ISSUE TITLE
Predictions

### ISSUE THREAD

**Issue by b-rodrigues** [B-Gendron/lhp#2]
Pour info, je pense qu'il y a un soucis avec les prédictions, ou comment elles sont présentées — ne vous en faites pas, je ne prends pas du tout le modèle en compte ni la qualité des prédictions pour la notation du cours, tout ce qui m'intéresse c'est "l'infrastructure" autour, et pour ça, tout est bon, mais j'ai quand même pensé que cela pouvait vous intéresser.

Par exemple, si vous mettez le genre sur "female" laissez l'âge sur 42 et mettez tous les facteurs de risque sur "No", vous obtenez le message suivant:

```
[1] "The predicted outcome for lung cancer condition is negative, with a probability of 0.001"
```

Le modèle ne semble pas très sûr de sa prédiction! Je pense que vous devez adapter cette ligne dans la fonction qui renvoie le message dans votre package `{lunglog}`:

https://github.com/B-Gendron/lunglog/blob/64dc9b8ec73b9f84092536dca8c5f002010f0d30/R/functions.R#L200

quand la prediction d'un cancer est "pas de cancer", il faut retourner 1 - proba, car la proba retournée est la proba d'un outcome positif (donc d'un cancer, d'où le .1%).

**Comment by B-Gendron** [comment]
Ah oui effectivement, j'avais oublié de régler ce problème. Merci d'avoir pris le temps de tester l'app !
